### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dougwilson** [expressjs/statusboard#2]
I'm curious: why are there over 400 releases on this repository? https://github.com/expressjs/statusboard/releases

Each release sends an email to any watchers on the repo (like me), which is getting completely crazy, lol. So I'm wondering if the sheer number of releases is either an accident (and thus bringing it up here makes you aware) or it's on purpose for testing, in which case I will unsubscribe from the repository for now.

**Comment by mikeal** [comment]
there were like 200+ last night so I’m guessing there was some kind of testing or accident ;)

**Comment by wesleytodd** [comment]
I have yet to be able to test the setup steps here I was using this repo to test the build steps.  One of those is to build a package and publish it to the github package regestry on each PR.  The goal of this would be in the future to let us install their PRs from the GPR to test.  The packages are all pre-release style like `v1.0.1-fe03750897519c0bb5dcd617a3f925d89d404c31.0` with the commit hash in the prerelease.

The reason there are 400 is because I didn't think it would be an issue and didnt turn it off as I was testing changes which required me to continually push last night.  If I had known it would email people I would have turned it off :)

**Comment by wesleytodd** [comment]
Also, it didn't email me, probably because I was the one triggering it.  So sorry to have spammed you all, I would have disabled that since it was not what I was testing if I had known.  I would for sure un-watch this one for now as I test out other actions which might also require "test via push".

**Comment by wesleytodd** [comment]
One learning from this is that before we enable something like this on one of the main repos, we should not publish a package for each push on a PR, that is just too much.  

I will look at making the job only publish if there is a specific label, or maybe I can get it to be manually triggered.  I will explore options.

**Comment by wesleytodd** [comment]
https://github.blog/changelog/2019-09-06-publishing-a-package-no-longer-creates-a-release-and-other-github-package-registry-updates/

> When publishing a package in GitHub Package Registry, a release and corresponding tag will no longer be created.

Closing this, as GitHub has realized the error of their ways :)
